name: "Feature Request"
description: Create a new ticket for a new feature request.
title: "[FEATURE REQUEST] - title"
labels: [
  "question"
]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the feature.
      placeholder: Describe in a few lines your feature request.
    validations:
      required: true
  - type: textarea
    id: basic_example
    attributes:
      label: "Basic Example"
      description: Indicate here some basic examples of your feature.
      placeholder: A few specific words about your feature request.
    validations:
      required: true
  - type: textarea
    id: reference_issues
    attributes:
      label: "Reference Issues."
      description: Common issues
      placeholder: "#Issues IDs"
    validations:
      required: false